name: sglpy

channels:
  - conda-forge

dependencies:
  - ipython=7.17.0
  - ipywidgets=7.5.1
  - jupyterlab=2.2.6
  - numpy=1.19.1
  - pip
  - python>=3.6
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - tqdm=4.48.2
  - pip:
      - copt==0.8.4
